# Generated by Django 5.2.1 on 2025-05-31 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100, verbose_name='氏名')),
                ('student_id', models.CharField(max_length=20, verbose_name='学籍番号')),
                ('student_email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shift_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='manager.shiftslot')),
            ],
        ),
    ]
