# Generated by Django 5.2.1 on 2025-05-31 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.CharField(choices=[('8:00〜9:00', '8:00〜9:00'), ('9:00〜10:30', '9:00〜10:30'), ('10:40〜12:10', '10:40〜12:10'), ('12:10〜13:00', '12:10〜13:00'), ('13:00〜14:30', '13:00〜14:30'), ('14:45〜16:15', '14:45〜16:15'), ('16:30〜18:00', '16:30〜18:00'), ('18:15〜19:45', '18:15〜19:45')], max_length=20)),
                ('capacity', models.PositiveSmallIntegerField(default=1)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['date', 'time_slot'],
                'unique_together': {('date', 'time_slot')},
            },
        ),
    ]
